### ISSUE TITLE
Unused arguments

### ISSUE THREAD

**Issue by tianchengzhe** [dynverse/ti_angle#2]
Running this method gives the following error:

>  Loading required namespace: dyncli
>  Failed with error:  ‘unused argument (quiet = TRUE)’
>  Loading required namespace: dyndimred
>  Failed with error:  ‘unused argument (quiet = TRUE)’

It seems that `quiet` should be changed to `quietly` in the following lines
`requireNamespace("dyncli", quiet = TRUE)`
`requireNamespace("dyndimred", quiet = TRUE)`

**Comment by rcannood** [comment]
Thanks @tianchengzhe! This was fixed in 68effa1.
